### PR TITLE
Data generation script

### PR DESCRIPTION
**Pull request by Vasanarul**
Please review when you have the chance!

### CODE REVIEW

**Review by jensenchelese — COMMENTED** [review]
I am wondering why all of the code is commented out?

**Comment by jchen0506** [comment]
The code looks good to me. Why are they all commented out?

**Comment by Vasanarul** [comment]
> I am wondering why all of the code is commented out?

Ah thanks for catching that! It was also supposed to show the uncommented code above that shows the same information, will have that resolved for tomorrow for everyone's reviews.

**Comment by orlando-apps** [comment]
Looks good.  I read thru assuming lines were not commented.

**Pull request merged**
